# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.12

# Mod Properties
mod_version=1.5.0
maven_group=com.autoeater
archives_base_name=auto-eater

# Dependencies
fabric_version=0.153.0+26.2
modmenu_version=20.0.0-alpha.1
